### ISSUE TITLE
Question about throw undefined/Promise.reject handling

### ISSUE THREAD

**Issue by polesskiy-dev** [xobotyi/await-of#1]
Hello, I just run in [https://npm.runkit.com/await-of](https://npm.runkit.com/await-of) 

```
const of = require("await-of").default

const f = () => Promise.reject();

let [res, err] = await of(f());

if (err) console.log('Error in of');

try {
    await f();
} catch (e){
    console.log('Error in try-catch');
}
```

and result is:
```
"Error in try-catch"
```

Same behavior would be in `throw Error` instead of `Promise.reject()`, maybe

**Comment by xobotyi** [comment]
Hmm.. Actually it works as supposed to: promise was rejected with `undefined` and `undefined` been passed to the `err` variable =\  
The code with `try-catch` handles it cause rejection wasnt handled at all, and if you'll add the same code as for first catch attempt:
```javascript
try {
    await f();
} catch (e){
    if (e)
    console.log('Error in try-catch');
}
```
It will have no logs at all.

As the rejection with empty value is a bad practice i wasn't counting on that. May be a good solution will be to return an error object in case of rejection with `undefined` value🤔

**Comment by polesskiy-dev** [comment]
@xobotyi but how can we determine in this example that Promise was actually rejected? I don't place `if (e) console.log('Error in try-catch');` to shed some light on fact that inside `catch` block we can actually understand that error actually appeares.

**Comment by xobotyi** [comment]
@polesskiy-dev committed a new version that will return an Error instance in case of `undefined` ot `null` value rejection.
